version: '3.7'
services:

  database:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD-password}
      POSTGRES_USER: ${DATABASE_USER-user}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - database
    ports:
      - 5432:5432
    volumes:
      - .:/var/lib/postgresql/data

  database-admin:
    container_name: adminer
    image: adminer:4.8.1-standalone
    restart: always
    networks:
      - database
    ports:
      - 8080:8080

networks:
  database:
    driver: bridge
