name: Deploy components to Github Pages

on:
  workflow_call:
    secrets:
      COLIBRI_GITHUB_TOKEN:
        description: Need this token for removing environments
        required: true
    inputs:
      testIsSuccess:
        description: Do not deploy if tests failed
        default: true
        type: boolean

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    if: (((github.event_name == 'pull_request' && contains(fromJSON('["opened", "reopened", "synchronize"]'), github.event.action)) || (github.event_name == 'push' && github.ref_name == 'main')) && inputs.testIsSuccess && always())
    environment:
      name: ${{ github.event_name == 'pull_request' && format('github-pages-{0}', github.head_ref) || 'github-pages' }}
      url: ${{ format('https://{0}.github.io/{1}/{2}/', github.event.repository.owner.login, github.event.repository.name, github.event_name == 'pull_request' && github.head_ref || github.event.repository.default_branch) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Set remote url
        run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Build components
        run: yarn workspace @colibri/components build
      - name: Upload artifacts
        run: |
          yarn gh-pages \
            --branch build \
            --dist ./packages/components/dist/ \
            --dest ${{ github.event_name == 'pull_request' && github.head_ref || github.event.repository.default_branch }} \
            --remove ${{ github.event_name == 'pull_request' && github.head_ref || github.event.repository.default_branch }} \
            --user "github-actions-bot <support+actions@github.com>"

  remove:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Remove folder with branch from build branch
        run: |
          git config --global user.email "github-actions-bot"
          git config --global user.name "support+actions@github.com"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git fetch origin build
          git switch build
          git rm ${{ github.head_ref }} -r
          git commit -a -n -m "remove ${{ github.event.pull_request.head.ref }}"
          git push origin build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Remove environment
        env:
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
          ENVIRONMENT_NAME: ${{ format('github-pages-{0}', github.head_ref) }}
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.COLIBRI_GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${OWNER}/${REPO}/environments/${ENVIRONMENT_NAME}
