name: Pull request

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - synchronize

jobs:
  test:
    if: ${{ !(github.event_name == 'pull_request' && github.event.action == 'closed') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        shell: bash
      - name: Lint code
        run: npm run lint
      - if: github.event_name == 'pull_request'
        name: Validate PR commits with commitlint
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Run tests
        run: npm run test

  deployment:
    if: ${{ always() }}
    needs: test
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      testIsSuccess: ${{ needs.test.result == 'success' }}
